# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@discordjs/builders-1.3.0" = {
      name = "_at_discordjs_slash_builders";
      packageName = "@discordjs/builders";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@discordjs/builders/-/builders-1.3.0.tgz";
        sha512 = "Pvca6Nw8Hp+n3N+Wp17xjygXmMvggbh5ywUsOYE2Et4xkwwVRwgzxDJiMUuYapPtnYt4w/8aKlf5khc8ipLvhg==";
      };
    };
    "@discordjs/collection-1.2.0" = {
      name = "_at_discordjs_slash_collection";
      packageName = "@discordjs/collection";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@discordjs/collection/-/collection-1.2.0.tgz";
        sha512 = "VvrrtGb7vbfPHzbhGq9qZB5o8FOB+kfazrxdt0OtxzSkoBuw9dURMkCwWizZ00+rDpiK2HmLHBZX+y6JsG9khw==";
      };
    };
    "@discordjs/rest-1.3.0" = {
      name = "_at_discordjs_slash_rest";
      packageName = "@discordjs/rest";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@discordjs/rest/-/rest-1.3.0.tgz";
        sha512 = "U6X5J+r/MxYpPTlHFuPxXEf92aKsBaD2teBC7sWkKILIr30O8c9+XshfL7KFBCavnAqS/qE+PF9fgRilO3N44g==";
      };
    };
    "@discordjs/util-0.1.0" = {
      name = "_at_discordjs_slash_util";
      packageName = "@discordjs/util";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@discordjs/util/-/util-0.1.0.tgz";
        sha512 = "e7d+PaTLVQav6rOc2tojh2y6FE8S7REkqLldq1XF4soCx74XB/DIjbVbVLtBemf0nLW77ntz0v+o5DytKwFNLQ==";
      };
    };
    "@sapphire/async-queue-1.5.0" = {
      name = "_at_sapphire_slash_async-queue";
      packageName = "@sapphire/async-queue";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sapphire/async-queue/-/async-queue-1.5.0.tgz";
        sha512 = "JkLdIsP8fPAdh9ZZjrbHWR/+mZj0wvKS5ICibcLrRI1j84UmLMshx5n9QmL8b95d4onJ2xxiyugTgSAX7AalmA==";
      };
    };
    "@sapphire/shapeshift-3.7.0" = {
      name = "_at_sapphire_slash_shapeshift";
      packageName = "@sapphire/shapeshift";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sapphire/shapeshift/-/shapeshift-3.7.0.tgz";
        sha512 = "A6vI1zJoxhjWo4grsxpBRBgk96SqSdjLX5WlzKp9H+bJbkM07mvwcbtbVAmUZHbi/OG3HLfiZ1rlw4BhH6tsBQ==";
      };
    };
    "@sapphire/snowflake-3.2.2" = {
      name = "_at_sapphire_slash_snowflake";
      packageName = "@sapphire/snowflake";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sapphire/snowflake/-/snowflake-3.2.2.tgz";
        sha512 = "ula2O0kpSZtX9rKXNeQMrHwNd7E4jPDJYUXmEGTFdMRfyfMw+FPyh04oKMjAiDuOi64bYgVkOV3MjK+loImFhQ==";
      };
    };
    "@tokenizer/token-0.3.0" = {
      name = "_at_tokenizer_slash_token";
      packageName = "@tokenizer/token";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tokenizer/token/-/token-0.3.0.tgz";
        sha512 = "OvjF+z51L3ov0OyAU0duzsYuvO01PH7x4t6DJx+guahgTnBHkhJdG7soQeTSFLWN3efnHyibZ4Z8l2EuWwJN3A==";
      };
    };
    "@types/node-18.8.5" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "18.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-18.8.5.tgz";
        sha512 = "Bq7G3AErwe5A/Zki5fdD3O6+0zDChhg671NfPjtIcbtzDNZTv4NPKMRFr7gtYPG7y+B8uTiNK4Ngd9T0FTar6Q==";
      };
    };
    "@types/ws-8.5.3" = {
      name = "_at_types_slash_ws";
      packageName = "@types/ws";
      version = "8.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ws/-/ws-8.5.3.tgz";
        sha512 = "6YOoWjruKj1uLf3INHH7D3qTXwFfEsg1kf3c0uDdSBJwfa/llkwIjrAGV7j7mVgGNbzTQ3HiHKKDXl6bJPD97w==";
      };
    };
    "busboy-1.6.0" = {
      name = "busboy";
      packageName = "busboy";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/busboy/-/busboy-1.6.0.tgz";
        sha512 = "8SFQbg/0hQ9xy3UNTB0YEnsNBbWfhf7RtnzpL7TkBiTBRfrQ9Fxcnz7VJsleJpyp6rVLvXiuORqjlHi5q+PYuA==";
      };
    };
    "discord-api-types-0.37.12" = {
      name = "discord-api-types";
      packageName = "discord-api-types";
      version = "0.37.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/discord-api-types/-/discord-api-types-0.37.12.tgz";
        sha512 = "SMBP4V6/A9mE7shBQAiTxNWnQlYTdiKMGvc7G23neayxaTJeFYh5FviJSWUa0BTdXcph1h/jT03Nbyv5XgZkzw==";
      };
    };
    "discord.js-14.6.0" = {
      name = "discord.js";
      packageName = "discord.js";
      version = "14.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/discord.js/-/discord.js-14.6.0.tgz";
        sha512 = "On1K7xpJZRe0KsziIaDih2ksYPhgxym/ZqV45i1f3yig4vUotikqs7qp5oXiTzQ/UTiNRCixUWFTh7vA1YBCqw==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "file-type-18.0.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "18.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-18.0.0.tgz";
        sha512 = "jjMwFpnW8PKofLE/4ohlhqwDk5k0NC6iy0UHAJFKoY1fQeGMN0GDdLgHQrvCbSpMwbqzoCZhRI5dETCZna5qVA==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "lodash.snakecase-4.1.1" = {
      name = "lodash.snakecase";
      packageName = "lodash.snakecase";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.snakecase/-/lodash.snakecase-4.1.1.tgz";
        sha512 = "QZ1d4xoBHYUeuouhEq3lk3Uq7ldgyFXGBhg04+oRLnIz8o9T65Eh+8YdroUwn846zchkA9yDsDl5CVVaV2nqYw==";
      };
    };
    "lodash.uniqwith-4.5.0" = {
      name = "lodash.uniqwith";
      packageName = "lodash.uniqwith";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.uniqwith/-/lodash.uniqwith-4.5.0.tgz";
        sha512 = "7lYL8bLopMoy4CTICbxygAUq6CdRJ36vFc80DucPueUee+d5NBRxz3FdT9Pes/HEx5mPoT9jwnsEJWz1N7uq7Q==";
      };
    };
    "peek-readable-5.0.0" = {
      name = "peek-readable";
      packageName = "peek-readable";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/peek-readable/-/peek-readable-5.0.0.tgz";
        sha512 = "YtCKvLUOvwtMGmrniQPdO7MwPjgkFBtFIrmfSbYmYuq3tKDV/mcfAhBth1+C3ru7uXIZasc/pHnb+YDYNkkj4A==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "readable-web-to-node-stream-3.0.2" = {
      name = "readable-web-to-node-stream";
      packageName = "readable-web-to-node-stream";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-web-to-node-stream/-/readable-web-to-node-stream-3.0.2.tgz";
        sha512 = "ePeK6cc1EcKLEhJFt/AebMCLL+GgSKhuygrZ/GLaKZYEecIgIECf4UaUuaByiGtzckwR4ain9VzUh95T1exYGw==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "streamsearch-1.1.0" = {
      name = "streamsearch";
      packageName = "streamsearch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamsearch/-/streamsearch-1.1.0.tgz";
        sha512 = "Mcc5wHehp9aXz1ax6bZUyY5afg9u2rv5cqQI3mRrYkGC8rW2hM02jWuwjtL++LS5qinSyhj2QfLyNsuc+VsExg==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strtok3-7.0.0" = {
      name = "strtok3";
      packageName = "strtok3";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strtok3/-/strtok3-7.0.0.tgz";
        sha512 = "pQ+V+nYQdC5H3Q7qBZAz/MO6lwGhoC2gOAjuouGf/VO0m7vQRh8QNMl2Uf6SwAtzZ9bOw3UIeBukEGNJl5dtXQ==";
      };
    };
    "token-types-5.0.1" = {
      name = "token-types";
      packageName = "token-types";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-types/-/token-types-5.0.1.tgz";
        sha512 = "Y2fmSnZjQdDb9W4w4r1tswlMHylzWIeOKpx0aZH9BgGtACHhrk3OkT52AzwcuqTRBZtvvnTjDBh8eynMulu8Vg==";
      };
    };
    "ts-mixer-6.0.1" = {
      name = "ts-mixer";
      packageName = "ts-mixer";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-mixer/-/ts-mixer-6.0.1.tgz";
        sha512 = "hvE+ZYXuINrx6Ei6D6hz+PTim0Uf++dYbK9FFifLNwQj+RwKquhQpn868yZsCtJYiclZF1u8l6WZxxKi+vv7Rg==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
    "undici-5.11.0" = {
      name = "undici";
      packageName = "undici";
      version = "5.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici/-/undici-5.11.0.tgz";
        sha512 = "oWjWJHzFet0Ow4YZBkyiJwiK5vWqEYoH7BINzJAJOLedZ++JpAlCbUktW2GQ2DS2FpKmxD/JMtWUUWl1BtghGw==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "ws-8.9.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.9.0.tgz";
        sha512 = "Ja7nszREasGaYUYCI2k4lCKIRTt+y7XuqVoHR44YpI49TtryyqbqvDMn5eqfW7e6HzTukDRIsXqzVHScqRcafg==";
      };
    };
  };
  args = {
    name = "new_limgrisen";
    packageName = "new_limgrisen";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@discordjs/builders-1.3.0"
      sources."@discordjs/collection-1.2.0"
      sources."@discordjs/rest-1.3.0"
      sources."@discordjs/util-0.1.0"
      sources."@sapphire/async-queue-1.5.0"
      sources."@sapphire/shapeshift-3.7.0"
      sources."@sapphire/snowflake-3.2.2"
      sources."@tokenizer/token-0.3.0"
      sources."@types/node-18.8.5"
      sources."@types/ws-8.5.3"
      sources."busboy-1.6.0"
      sources."discord-api-types-0.37.12"
      sources."discord.js-14.6.0"
      sources."fast-deep-equal-3.1.3"
      sources."file-type-18.0.0"
      sources."ieee754-1.2.1"
      sources."inherits-2.0.4"
      sources."lodash.snakecase-4.1.1"
      sources."lodash.uniqwith-4.5.0"
      sources."peek-readable-5.0.0"
      sources."readable-stream-3.6.0"
      sources."readable-web-to-node-stream-3.0.2"
      sources."safe-buffer-5.2.1"
      sources."streamsearch-1.1.0"
      sources."string_decoder-1.3.0"
      sources."strtok3-7.0.0"
      sources."token-types-5.0.1"
      sources."ts-mixer-6.0.1"
      sources."tslib-2.4.0"
      sources."undici-5.11.0"
      sources."util-deprecate-1.0.2"
      sources."ws-8.9.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A bot for managing CTFs";
      license = "AGPL-3.0-or-later";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
